export default {
  Product: require('../assets/images/Product.png'),
  DSC08172850x567: require('../assets/images/DSC08172850x567.jpeg'),
  LG8KQNEDMiniLED030: require('../assets/images/LG8KQNEDMiniLED030.jpg'),
  C000200024804Still004: require('../assets/images/C000200024804Still004.png'),
  _50076938783940850x540: require('../assets/images/50076938783940850x540.png'),
  Trev: require('../assets/images/Trev.jpeg'),
  Eftmblack: require('../assets/images/Eftmblack.png'),
  EFTMLOGO2479x1: require('../assets/images/EFTMLOGO2479x(1).png'),
  GooglePodcastsIcon: require('../assets/images/GooglePodcastsIcon.png'),
  Bluegradient: require('../assets/images/Bluegradient.png'),
  Angryimg4: require('../assets/images/Angryimg(4).png'),
  Angryimg3: require('../assets/images/Angryimg(3).png'),
  Angryimg2: require('../assets/images/Angryimg(2).png'),
  Angryimg1: require('../assets/images/Angryimg(1).png'),
  Angryimg: require('../assets/images/Angryimg.png'),
  Elliot: require('../assets/images/Elliot.jpg'),
  Eftmlogowhite: require('../assets/images/Eftmlogowhite.png'),
  EzgifcomGifMaker: require('../assets/images/EzgifcomGifMaker.png'),
  DraftbitIcon: require('../assets/images/DraftbitIcon.png'),
  DraftbitTeamPhoto: require('../assets/images/DraftbitTeamPhoto.jpg'),
  EFTMHIRESLOGO2016: require('../assets/images/EFTMHIRESLOGO2016.png'),
};
