export default {
  GooglePodcastsIcon: require('../assets/images/GooglePodcastsIcon.png'),
  Bluegradient: require('../assets/images/Bluegradient.png'),
  Angryimg4: require('../assets/images/Angryimg(4).png'),
  Angryimg3: require('../assets/images/Angryimg(3).png'),
  Angryimg2: require('../assets/images/Angryimg(2).png'),
  Angryimg1: require('../assets/images/Angryimg(1).png'),
  Angryimg: require('../assets/images/Angryimg.png'),
  Elliot: require('../assets/images/Elliot.jpg'),
  Eftmlogowhite: require('../assets/images/Eftmlogowhite.png'),
  EzgifcomGifMaker: require('../assets/images/EzgifcomGifMaker.png'),
  DraftbitIcon: require('../assets/images/DraftbitIcon.png'),
  DraftbitTeamPhoto: require('../assets/images/DraftbitTeamPhoto.jpg'),
  EFTMHIRESLOGO2016: require('../assets/images/EFTMHIRESLOGO2016.png'),
};
